UPDATE farmasi_quiz_questions SET option_a = 'On-Duty', option_b = 'Off-Duty', option_c = 'Back in Service', option_d = 'Not in Service', option_e = 'Copy / Understood', correct_option = 'a' WHERE question_code IN ('FQ-001');
UPDATE farmasi_quiz_questions SET option_a = '10-8', option_b = '10-42', option_c = '10-41', option_d = '10-7', option_e = '10-4', correct_option = 'c' WHERE question_code IN ('FQ-002');
UPDATE farmasi_quiz_questions SET option_a = 'Off-Duty', option_b = 'Not in Service', option_c = 'On-Duty', option_d = 'Back in Service', option_e = 'Meeting', correct_option = 'a' WHERE question_code IN ('FQ-003');
UPDATE farmasi_quiz_questions SET option_a = '10-7', option_b = '10-8', option_c = '10-1', option_d = '10-42', option_e = '10-41', correct_option = 'd' WHERE question_code IN ('FQ-004');
UPDATE farmasi_quiz_questions SET option_a = 'Meeting', option_b = 'Repeat', option_c = 'Copy / Understood', option_d = 'Good Signal', option_e = 'Back in Service', correct_option = 'a' WHERE question_code IN ('FQ-005');
UPDATE farmasi_quiz_questions SET option_a = '10-9', option_b = '10-1', option_c = '10-2', option_d = '10-4', option_e = '10-8', correct_option = 'b' WHERE question_code IN ('FQ-006');
UPDATE farmasi_quiz_questions SET option_a = 'Copy / Understood', option_b = 'Good Signal', option_c = 'Meeting', option_d = 'Repeat', option_e = 'On-Duty', correct_option = 'b' WHERE question_code IN ('FQ-007');
UPDATE farmasi_quiz_questions SET option_a = '10-4', option_b = '10-9', option_c = '10-2', option_d = '10-1', option_e = '10-7', correct_option = 'c' WHERE question_code IN ('FQ-008');
UPDATE farmasi_quiz_questions SET option_a = 'Copy / Understood', option_b = 'Good Signal', option_c = 'Back in Service', option_d = 'Not in Service', option_e = 'Repeat', correct_option = 'a' WHERE question_code IN ('FQ-009');
UPDATE farmasi_quiz_questions SET option_a = '10-2', option_b = '10-4', option_c = '10-8', option_d = '10-9', option_e = '10-7', correct_option = 'b' WHERE question_code IN ('FQ-010');
UPDATE farmasi_quiz_questions SET option_a = 'Off-Duty', option_b = 'Back in Service', option_c = 'Not in Service', option_d = 'Meeting', option_e = 'On-Duty', correct_option = 'c' WHERE question_code IN ('FQ-011');
UPDATE farmasi_quiz_questions SET option_a = '10-42', option_b = '10-8', option_c = '10-7', option_d = '10-41', option_e = '10-1', correct_option = 'c' WHERE question_code IN ('FQ-012');
UPDATE farmasi_quiz_questions SET option_a = 'Good Signal', option_b = 'On-Duty', option_c = 'Back in Service', option_d = 'Repeat', option_e = 'Not in Service', correct_option = 'c' WHERE question_code IN ('FQ-013');
UPDATE farmasi_quiz_questions SET option_a = '10-7', option_b = '10-8', option_c = '10-4', option_d = '10-2', option_e = '10-42', correct_option = 'b' WHERE question_code IN ('FQ-014');
UPDATE farmasi_quiz_questions SET option_a = 'Repeat', option_b = 'Copy / Understood', option_c = 'Meeting', option_d = 'Good Signal', option_e = 'Off-Duty', correct_option = 'a' WHERE question_code IN ('FQ-015');
UPDATE farmasi_quiz_questions SET option_a = '10-2', option_b = '10-9', option_c = '10-4', option_d = '10-1', option_e = '10-8', correct_option = 'b' WHERE question_code IN ('FQ-016');
UPDATE farmasi_quiz_questions SET option_a = 'Nama depan to Dispatch, reporting status kode', option_b = 'Dispatch to unit, status received kode', option_c = 'Nama lengkap to seluruh unit, meminta repeat status', option_d = 'Kode terlebih dahulu lalu nama belakang ke Dispatch', option_e = 'Nama depan to rumah sakit, requesting channel change', correct_option = 'a' WHERE question_code IN ('FQ-017');
UPDATE farmasi_quiz_questions SET option_a = 'Sedang rapat internal', option_b = 'Mulai bertugas', option_c = 'Meminta pesan diulang', option_d = 'Sedang tidak aktif sementara', option_e = 'Mengakhiri tugas', correct_option = 'b' WHERE question_code IN ('FQ-018');

UPDATE farmasi_quiz_questions SET option_a = 'ketorolac / ibuprofen', option_b = 'ranitidine / omeprazole', option_c = 'lidocaine / ceftriaxone', option_d = 'natrium diklofenak / dexamethasone', option_e = 'vitamin C / neurobion', correct_option = 'b' WHERE question_code IN ('FQ-019','FQ-020');
UPDATE farmasi_quiz_questions SET option_a = 'ranitidine / omeprazole', option_b = 'neurobion / vit c / biocombin', option_c = 'ketorolac / ibuprofen', option_d = 'lidocaine / ceftriaxone', option_e = 'NaCl / bioplacenton', correct_option = 'b' WHERE question_code IN ('FQ-021','FQ-022');
UPDATE farmasi_quiz_questions SET option_a = 'natrium diklofenak', option_b = 'ketorolac', option_c = 'neurobion', option_d = 'omeprazole', option_e = 'lidocaine', correct_option = 'a' WHERE question_code IN ('FQ-023','FQ-024');
UPDATE farmasi_quiz_questions SET option_a = 'spinal board', option_b = 'elastic bandage', option_c = 'ice cold pack (ICP)', option_d = 'warm compress pack', option_e = 'arm sling', correct_option = 'c' WHERE question_code IN ('FQ-025','FQ-026');
UPDATE farmasi_quiz_questions SET option_a = 'posisikan area cedera lebih tinggi dari jantung', option_b = 'gerakkan sendi sesering mungkin agar tidak kaku', option_c = 'kompres hangat segera setelah cedera', option_d = 'lepas balutan tiap beberapa menit', option_e = 'biarkan tungkai menggantung ke bawah', correct_option = 'a' WHERE question_code IN ('FQ-027','FQ-028');
UPDATE farmasi_quiz_questions SET option_a = 'bioplacenton', option_b = 'heparin sodium gel / thrombopop gel', option_c = 'neosporin', option_d = 'mupirocin ointment', option_e = 'povidone iodine gel', correct_option = 'b' WHERE question_code IN ('FQ-029','FQ-030');
UPDATE farmasi_quiz_questions SET option_a = 'bioplacenton', option_b = 'neosporin', option_c = 'thrombopop gel', option_d = 'heparin sodium gel', option_e = 'silver sulfadiazine', correct_option = 'b' WHERE question_code IN ('FQ-031','FQ-032');
UPDATE farmasi_quiz_questions SET option_a = 'steri strips', option_b = 'elastic bandage', option_c = 'arm sling', option_d = 'pedicle screw', option_e = 'tourniquet strap', correct_option = 'a' WHERE question_code IN ('FQ-033','FQ-034');
UPDATE farmasi_quiz_questions SET option_a = 'melakukan CPR', option_b = 'memberikan analgesik intramuskular', option_c = 'memasang arm sling', option_d = 'menjahit area luka', option_e = 'melakukan intubasi tanpa pemeriksaan nadi', correct_option = 'a' WHERE question_code IN ('FQ-035','FQ-036');
UPDATE farmasi_quiz_questions SET option_a = 'lidocaine', option_b = 'bupivacaine', option_c = 'midazolam', option_d = 'omeprazole', option_e = 'ketorolac', correct_option = 'a' WHERE question_code IN ('FQ-037','FQ-038');
UPDATE farmasi_quiz_questions SET option_a = 'observasi di lokasi hingga 24 jam', option_b = 'segera bawa pasien ke rumah sakit', option_c = 'cukup balut dan izinkan pulang', option_d = 'lakukan fisioterapi awal di tempat', option_e = 'lanjutkan tindakan hanya bila pasien sadar penuh', correct_option = 'b' WHERE question_code IN ('FQ-039','FQ-040');
UPDATE farmasi_quiz_questions SET option_a = 'NaCl', option_b = 'alkohol 70%', option_c = 'hydrogen peroxide', option_d = 'povidone iodine pekat', option_e = 'chlorhexidine scrub', correct_option = 'a' WHERE question_code IN ('FQ-041','FQ-042');
UPDATE farmasi_quiz_questions SET option_a = 'silver sulfadiazine', option_b = 'bioplacenton', option_c = 'neosporin', option_d = 'thrombopop gel', option_e = 'heparin sodium gel', correct_option = 'b' WHERE question_code IN ('FQ-043','FQ-044');

UPDATE farmasi_quiz_questions SET option_a = 'Resume operasi', option_b = 'SKB', option_c = 'Surat rujukan radiologi', option_d = 'Surat cuti kerja', option_e = 'Kuitansi pembayaran lama', correct_option = 'b' WHERE question_code IN ('FQ-045','FQ-046');
UPDATE farmasi_quiz_questions SET option_a = 'ID Card', option_b = 'kartu anggota EMS', option_c = 'slip gaji terakhir', option_d = 'surat cuti', option_e = 'voucher revive', correct_option = 'a' WHERE question_code IN ('FQ-047','FQ-048');
UPDATE farmasi_quiz_questions SET option_a = 'ruang observasi ICU', option_b = 'ruang rawat inap', option_c = 'ruang radiologi', option_d = 'ruang operasi', option_e = 'toilet umum', correct_option = 'b' WHERE question_code IN ('FQ-049','FQ-050');
UPDATE farmasi_quiz_questions SET option_a = 'liur', option_b = 'urine', option_c = 'keringat', option_d = 'air liur lambung', option_e = 'udara ekspirasi', correct_option = 'b' WHERE question_code IN ('FQ-051','FQ-052');
UPDATE farmasi_quiz_questions SET option_a = 'langsung saat itu juga', option_b = '7 hari kemudian', option_c = 'sehari setelah pengambilan sampel', option_d = '3 hari kemudian', option_e = 'setelah 1 bulan', correct_option = 'c' WHERE question_code IN ('FQ-053','FQ-054');
UPDATE farmasi_quiz_questions SET option_a = '10k', option_b = '25k', option_c = '15k', option_d = '20k', option_e = '30k', correct_option = 'c' WHERE question_code IN ('FQ-055','FQ-056');
UPDATE farmasi_quiz_questions SET option_a = 'Apakah Anda memiliki riwayat penyakit ginjal atau gangguan saluran kemih?', option_b = 'Apakah Anda rutin begadang karena shift malam?', option_c = 'Apakah Anda punya alergi makanan laut?', option_d = 'Apakah Anda pernah dirawat karena cedera olahraga?', option_e = 'Apakah Anda pernah menjalani operasi kecil dalam 1 tahun terakhir?', correct_option = 'a' WHERE question_code IN ('FQ-057','FQ-058');
UPDATE farmasi_quiz_questions SET option_a = '30 hari terakhir', option_b = '1 hari terakhir', option_c = '14 hari terakhir', option_d = '7 hari terakhir', option_e = '90 hari terakhir', correct_option = 'd' WHERE question_code IN ('FQ-059','FQ-060');
UPDATE farmasi_quiz_questions SET option_a = 'Apakah Anda pernah menjalani rehabilitasi terkait penyalahgunaan zat?', option_b = 'Apakah Anda pernah ditolak saat medical check-up kerja?', option_c = 'Apakah Anda pernah menerima transfusi darah?', option_d = 'Apakah Anda pernah kehilangan kesadaran setelah olahraga berat?', option_e = 'Apakah Anda pernah mengalami alergi antibiotik?', correct_option = 'a' WHERE question_code IN ('FQ-061','FQ-062');
UPDATE farmasi_quiz_questions SET option_a = 'tertutup untuk diri sendiri', option_b = 'tanpa identitas', option_c = 'paksa tanpa penjelasan', option_d = 'diam-diam', option_e = 'sukarela', correct_option = 'e' WHERE question_code IN ('FQ-063','FQ-064');
UPDATE farmasi_quiz_questions SET option_a = 'berbaring dan tetap rileks', option_b = 'duduk tegak sambil menahan napas', option_c = 'berjalan pelan agar sirkulasi lancar', option_d = 'makan ringan agar tidak pusing', option_e = 'menggerakkan lengan terus-menerus', correct_option = 'a' WHERE question_code IN ('FQ-065','FQ-066');
UPDATE farmasi_quiz_questions SET option_a = 'karena perlu validasi administrasi dari HRD', option_b = 'karena akan dilakukan uji lab terlebih dahulu', option_c = 'karena dokter harus menunggu persetujuan direktur', option_d = 'karena hasil harus dikonfirmasi oleh kepolisian', option_e = 'karena pasien harus observasi 24 jam', correct_option = 'b' WHERE question_code IN ('FQ-067','FQ-068');

UPDATE farmasi_quiz_questions SET option_a = 'ungu', option_b = 'hijau', option_c = 'biru', option_d = 'kuning', option_e = 'merah', correct_option = 'b' WHERE question_code IN ('FQ-069','FQ-070');
UPDATE farmasi_quiz_questions SET option_a = '$150', option_b = '$250', option_c = '$300', option_d = '$200', option_e = '$350', correct_option = 'd' WHERE question_code IN ('FQ-071','FQ-072');
UPDATE farmasi_quiz_questions SET option_a = 'ungu', option_b = 'hijau', option_c = 'biru', option_d = 'putih', option_e = 'merah', correct_option = 'a' WHERE question_code IN ('FQ-073','FQ-074');
UPDATE farmasi_quiz_questions SET option_a = '$300', option_b = '$350', option_c = '$200', option_d = '$400', option_e = '$250', correct_option = 'b' WHERE question_code IN ('FQ-075','FQ-076');
UPDATE farmasi_quiz_questions SET option_a = 'pihak manajemen rumah sakit', option_b = 'pasien', option_c = 'petugas penerima voucher', option_d = 'pemerintah', option_e = 'bagian keuangan EMS', correct_option = 'b' WHERE question_code IN ('FQ-077','FQ-078');
UPDATE farmasi_quiz_questions SET option_a = 'disimpan untuk reimbursement mingguan', option_b = 'difotokopi dan dikembalikan ke pasien', option_c = 'use voucher agar terstempel', option_d = 'diserahkan langsung ke kasir tanpa proses', option_e = 'ditukar dengan obat farmasi', correct_option = 'c' WHERE question_code IN ('FQ-079','FQ-080');
UPDATE farmasi_quiz_questions SET option_a = 'pimpinan', option_b = 'bagian radiologi', option_c = 'kasir farmasi', option_d = 'dokter operator', option_e = 'tim administrasi umum', correct_option = 'a' WHERE question_code IN ('FQ-081','FQ-082');
UPDATE farmasi_quiz_questions SET option_a = 'supplier alat medis', option_b = 'government', option_c = 'bagian payroll rumah sakit', option_d = 'kepolisian', option_e = 'dispatch', correct_option = 'b' WHERE question_code IN ('FQ-083','FQ-084');
UPDATE farmasi_quiz_questions SET option_a = 'gratis penuh untuk seluruh tindakan', option_b = 'potongan biaya 25%', option_c = 'potongan biaya 50%', option_d = 'cukup menggunakan voucher hijau', option_e = 'tidak mendapat keringanan', correct_option = 'c' WHERE question_code IN ('FQ-085','FQ-086');
UPDATE farmasi_quiz_questions SET option_a = '1 kali', option_b = '2 kali', option_c = '3 kali', option_d = 'sesuai kebutuhan medis', option_e = 'tidak dibatasi selama on duty', correct_option = 'a' WHERE question_code IN ('FQ-087','FQ-088');

UPDATE farmasi_quiz_questions SET option_a = 'setiap individu yang resmi ditetapkan sebagai tenaga medis di Roxwood Hospital', option_b = 'seluruh anggota manajemen rumah sakit dan pasien rawat inap', option_c = 'seluruh tenaga penunjang rumah sakit tanpa pengangkatan resmi', option_d = 'setiap warga yang pernah menerima perawatan medis di Roxwood Hospital', option_e = 'seluruh pemegang radio channel 99', correct_option = 'a' WHERE question_code IN ('FQ-089','FQ-090');
UPDATE farmasi_quiz_questions SET option_a = 'saat anggota mengganti jabatan sementara', option_b = 'setelah anggota cuti lebih dari 7 hari', option_c = 'ketika anggota mengundurkan diri atau diberhentikan', option_d = 'ketika anggota pindah unit kerja internal', option_e = 'saat anggota menyelesaikan training', correct_option = 'c' WHERE question_code IN ('FQ-091','FQ-092');
UPDATE farmasi_quiz_questions SET option_a = 'mendapat surat teguran otomatis', option_b = 'gugur keanggotaannya', option_c = 'dipindah ke status cuti', option_d = 'dinas sementara dibekukan', option_e = 'naik evaluasi ke HRD', correct_option = 'b' WHERE question_code IN ('FQ-093','FQ-094');
UPDATE farmasi_quiz_questions SET option_a = '3 hari', option_b = '5 hari', option_c = '7 hari', option_d = '10 hari', option_e = '14 hari', correct_option = 'b' WHERE question_code IN ('FQ-095','FQ-096');
UPDATE farmasi_quiz_questions SET option_a = '5 hari', option_b = '10 hari', option_c = '7 hari', option_d = '14 hari', option_e = '21 hari', correct_option = 'c' WHERE question_code IN ('FQ-097','FQ-098');
UPDATE farmasi_quiz_questions SET option_a = 'izin dari rekan satu tim yang senior', option_b = 'izin dari atasan yang bertugas', option_c = 'izin dari pasien yang ditangani', option_d = 'tanpa izin bila kondisi sepi', option_e = 'izin dari petugas dispatch', correct_option = 'b' WHERE question_code IN ('FQ-099','FQ-100');
UPDATE farmasi_quiz_questions SET option_a = 'presentasi akhir dan evaluasi absensi', option_b = 'ujian kompetensi paramedic serta pelatihan asisten operasi dan/atau kompetensi lain', option_c = 'penilaian administratif dan pembagian seragam tetap', option_d = 'tes radio dan tes kendaraan dinas', option_e = 'wawancara manajemen tanpa ujian tertulis', correct_option = 'b' WHERE question_code IN ('FQ-101','FQ-102');
UPDATE farmasi_quiz_questions SET option_a = 'praktik lapangan', option_b = 'tertulis', option_c = 'wawancara panel', option_d = 'simulasi radio', option_e = 'presentasi kasus', correct_option = 'b' WHERE question_code IN ('FQ-103','FQ-104');
UPDATE farmasi_quiz_questions SET option_a = 'tes paramedic', option_b = 'tes kedisiplinan umum', option_c = 'tes sekretariat medis', option_d = 'tes penjualan farmasi', option_e = 'tes administrasi kepegawaian', correct_option = 'a' WHERE question_code IN ('FQ-105','FQ-106');
UPDATE farmasi_quiz_questions SET option_a = 'cukup mengaktifkan kembali akun lama', option_b = 'mengikuti seluruh ketentuan dan prosedur anggota baru', option_c = 'hanya menyerahkan surat rekomendasi dari atasan lama', option_d = 'cukup lulus tes wawancara ulang', option_e = 'langsung aktif setelah verifikasi HRD', correct_option = 'b' WHERE question_code IN ('FQ-107','FQ-108');
UPDATE farmasi_quiz_questions SET option_a = 'Direktur dan Manajemen Roxwood Hospital', option_b = 'Komisi Disiplin EMS', option_c = 'HRD rumah sakit bersama kepala unit', option_d = 'seluruh dokter spesialis aktif', option_e = 'tim evaluasi mingguan EMS', correct_option = 'a' WHERE question_code IN ('FQ-109','FQ-110');
UPDATE farmasi_quiz_questions SET option_a = 'baju bebas rapi', option_b = 'seragam training', option_c = 'seragam paramedic', option_d = 'jas operasi umum', option_e = 'hazmat permanen', correct_option = 'b' WHERE question_code IN ('FQ-111','FQ-112');

UPDATE farmasi_quiz_questions SET option_a = '75', option_b = '85', option_c = '80', option_d = '90', option_e = '70', correct_option = 'c' WHERE question_code IN ('FQ-113','FQ-114');
UPDATE farmasi_quiz_questions SET option_a = '7 jam', option_b = '10 jam', option_c = '12 jam', option_d = '15 jam', option_e = '20 jam', correct_option = 'b' WHERE question_code IN ('FQ-115','FQ-116');
UPDATE farmasi_quiz_questions SET option_a = 'sertifikat medical class', option_b = 'sertifikat co-ass', option_c = 'sertifikat basic trauma', option_d = 'sertifikat operasi minor', option_e = 'sertifikat radio EMS', correct_option = 'a' WHERE question_code IN ('FQ-117','FQ-118');
UPDATE farmasi_quiz_questions SET option_a = '2 tindakan operasi', option_b = '3 tindakan operasi', option_c = '4 tindakan operasi', option_d = '5 tindakan operasi', option_e = '3 operasi mayor', correct_option = 'b' WHERE question_code IN ('FQ-119','FQ-120');
UPDATE farmasi_quiz_questions SET option_a = '75', option_b = '85', option_c = '90', option_d = '80', option_e = '95', correct_option = 'd' WHERE question_code IN ('FQ-121','FQ-122');
UPDATE farmasi_quiz_questions SET option_a = '2 operasi minor', option_b = '4 operasi minor', option_c = '3 operasi minor', option_d = '5 operasi minor', option_e = '3 operasi mayor', correct_option = 'c' WHERE question_code IN ('FQ-123','FQ-124');
UPDATE farmasi_quiz_questions SET option_a = '1 operasi mayor', option_b = '2 operasi mayor', option_c = '3 operasi mayor', option_d = '2 operasi minor', option_e = '4 operasi mayor', correct_option = 'b' WHERE question_code IN ('FQ-125','FQ-126');
UPDATE farmasi_quiz_questions SET option_a = '80', option_b = '85', option_c = '90', option_d = '75', option_e = '88', correct_option = 'b' WHERE question_code IN ('FQ-127','FQ-128');
UPDATE farmasi_quiz_questions SET option_a = '14 hari internasional', option_b = '20 hari internasional', option_c = '30 hari internasional', option_d = '10 hari internasional', option_e = '21 hari internasional', correct_option = 'b' WHERE question_code IN ('FQ-129','FQ-130');
UPDATE farmasi_quiz_questions SET option_a = 'Program Dokter Residen sesuai spesialisasi yang dipilih', option_b = 'Program studi administrasi rumah sakit', option_c = 'Program rotasi kendaraan dinas', option_d = 'Program evaluasi payroll mingguan', option_e = 'Program sertifikasi radiologi dasar', correct_option = 'a' WHERE question_code IN ('FQ-131','FQ-132');
UPDATE farmasi_quiz_questions SET option_a = 'dokter umum', option_b = 'co-ass', option_c = 'paramedic', option_d = 'dokter spesialis', option_e = 'manager EMS', correct_option = 'c' WHERE question_code IN ('FQ-133','FQ-134');
UPDATE farmasi_quiz_questions SET option_a = 'tingkat paramedic', option_b = 'tingkat dokter umum', option_c = 'tingkat co-ass', option_d = 'tingkat residen', option_e = 'tingkat spesialis', correct_option = 'c' WHERE question_code IN ('FQ-135','FQ-136');

UPDATE farmasi_quiz_questions SET option_a = 'Training', option_b = 'Paramedic', option_c = 'Co-Ass', option_d = 'Dokter Umum', option_e = 'Dokter Spesialis', correct_option = 'a' WHERE question_code IN ('FQ-137','FQ-138');
UPDATE farmasi_quiz_questions SET option_a = 'satu anggota dengan jabatan lebih tinggi', option_b = 'minimal satu rekan setingkat training', option_c = 'petugas non medis yang standby di rumah sakit', option_d = 'paramedic atau co-ass saja', option_e = 'siapa pun yang menguasai radio', correct_option = 'a' WHERE question_code IN ('FQ-139','FQ-140');
UPDATE farmasi_quiz_questions SET option_a = '2 trainee', option_b = '4 trainee', option_c = '3 trainee', option_d = '5 trainee', option_e = '6 trainee', correct_option = 'c' WHERE question_code IN ('FQ-141','FQ-142');
UPDATE farmasi_quiz_questions SET option_a = 'Training', option_b = 'Paramedic', option_c = 'Dokter Umum', option_d = 'Co-Ass', option_e = 'Dokter Spesialis', correct_option = 'b' WHERE question_code IN ('FQ-143','FQ-144');
UPDATE farmasi_quiz_questions SET option_a = 'Paramedic', option_b = 'Dokter Umum', option_c = 'Co-Ass', option_d = 'Dokter Spesialis', option_e = 'Training', correct_option = 'c' WHERE question_code IN ('FQ-145','FQ-146');
UPDATE farmasi_quiz_questions SET option_a = 'Co-Ass', option_b = 'Paramedic', option_c = 'Dokter Spesialis', option_d = 'Dokter Umum', option_e = 'Training', correct_option = 'a' WHERE question_code IN ('FQ-147','FQ-148');
UPDATE farmasi_quiz_questions SET option_a = 'pasien hidup', option_b = 'pasien meninggal', option_c = 'anggota EMS aktif', option_d = 'seluruh korban kecelakaan lalu lintas', option_e = 'pasien rawat inap pasca operasi', correct_option = 'a' WHERE question_code IN ('FQ-149','FQ-150');
UPDATE farmasi_quiz_questions SET option_a = 'responding sinyal di daerah darat', option_b = 'pengangkutan pasien operasi mayor', option_c = 'kendaraan dinas administrasi umum', option_d = 'antar jemput surat rahasia', option_e = 'transportasi staf non medis', correct_option = 'a' WHERE question_code IN ('FQ-151','FQ-152');
UPDATE farmasi_quiz_questions SET option_a = 'respon area pegunungan sulit', option_b = 'pembuatan KTA atau perjalanan dinas untuk perjanjian', option_c = 'mobilisasi tim operasi lapangan', option_d = 'kendaraan penjualan farmasi keliling', option_e = 'kendaraan khusus pengawalan polisi', correct_option = 'b' WHERE question_code IN ('FQ-153','FQ-154');
UPDATE farmasi_quiz_questions SET option_a = 'area yang sulit dijangkau oleh kendaraan darat', option_b = 'daerah yang sulit dijangkau mobil', option_c = 'perjalanan dinas untuk perjanjian', option_d = 'responding sinyal di daerah darat', option_e = 'pengangkutan logistik farmasi ringan', correct_option = 'a' WHERE question_code IN ('FQ-155','FQ-156');
UPDATE farmasi_quiz_questions SET option_a = 'daerah yang sulit dijangkau mobil', option_b = 'daerah yang membutuhkan pengawalan polisi', option_c = 'perjalanan antarkota untuk administrasi', option_d = 'transportasi pasien pasca operasi', option_e = 'respon udara jarak jauh', correct_option = 'a' WHERE question_code IN ('FQ-157','FQ-158');
UPDATE farmasi_quiz_questions SET option_a = 'saat bertugas', option_b = 'saat cuti panjang', option_c = 'saat menerima gaji', option_d = 'saat off duty tetapi berada di rumah sakit', option_e = 'saat mengikuti pelatihan non medis', correct_option = 'a' WHERE question_code IN ('FQ-159','FQ-160');

UPDATE farmasi_quiz_session_questions sq
JOIN farmasi_quiz_questions q ON q.id = sq.question_id
SET
    sq.option_a = q.option_a,
    sq.option_b = q.option_b,
    sq.option_c = q.option_c,
    sq.option_d = q.option_d,
    sq.option_e = q.option_e,
    sq.correct_option = q.correct_option
WHERE q.question_code BETWEEN 'FQ-001' AND 'FQ-160'
  AND sq.selected_option IS NULL;
