-- Keep persisted AI templates compatible with model-owned clinical completion.
-- User/medical staff provides short source facts; model AI composes case-specific workflow.
-- Runtime guardrails still block unsupported measurements, findings, results, and completed actions.

UPDATE system_ai_prompt_templates
SET user_prompt_template = 'ANAMNESIS / TEMUAN MEDIS / KONDISI FISIK DARI USER:\n{{anamnesis}}\n\nTUGAS MODEL AI: Input boleh singkat. Rangkai laporan lengkap, berbeda sesuai kasus, dan berbasis SOP: narasi klinis, diagnosis kerja atau dugaan, diagnosis banding bila relevan, prioritas penilaian, ABCDE bila diindikasikan, rekomendasi pemeriksaan, rencana tindakan, tahapan, dan rujukan SOP. Jangan mengubah rencana/dugaan menjadi fakta pasien, angka pengukuran, hasil pemeriksaan, tindakan selesai, hasil operasi, atau prognosis. Gunakan Data belum tersedia hanya untuk fakta aktual yang memang tidak ada. M3 = fleksi abnormal/dekortikasi dan M4 = withdrawal/menarik diri normal adalah respons berbeda; pilih satu dan jangan menulis fleksi abnormal/withdrawal sebagai sinonim. Pada trauma kepala dengan kecurigaan peningkatan tekanan intrakranial, Disability wajib memuat pupil; anisokor/dilatasi dengan tanda herniasi akut membolehkan rencana operasi cito tanpa menunggu CT, selain itu tulis rencana tentatif — menunggu hasil CT scan. Hipotensi permisif/permissive hypotension hanya untuk strategi resusitasi cairan, bukan temuan TTV mentah. Cek kesesuaian fisiologis antara mekanisme, volume, lokasi cedera, derajat syok, dan penurunan kesadaran. Jika cedera teridentifikasi tidak cukup menjelaskan syok berat atau GCS rendah, jangan mengatribusikan semuanya ke cedera tunggal; tulis RED FLAG dengan frasa wajib, curigai cedera tambahan tersembunyi, dan minta secondary survey menyeluruh serta pencitraan tambahan. Semua pemeriksaan yang disebut di bagian mana pun laporan, termasuk Section 4 Status Rencana Operasi, wajib tercantum di Section 6 Rekomendasi Pemeriksaan Penunjang; jangan tulis menunggu hasil CT scan bila CT scan tidak tercantum di radiologi. Tungkai berarti ekstremitas bawah/kaki; tangan dan jari memakai ekstremitas atas, tangan, atau jari tangan.'
WHERE feature_key = 'ai_diagnosis_assistant';

UPDATE system_ai_prompt_templates
SET user_prompt_template = 'JENIS OPERASI: {{jenis_operasi}}\nJENIS ANESTESI: {{jenis_anestesi}}\nTINGKAT KOMPLEKSITAS: {{kompleksitas}}\nJUMLAH LANGKAH: {{jumlah_langkah}}\nKASUS MEDIS / TINDAKAN DARI USER:\n{{kasus_tindakan}}\n\nTUGAS MODEL AI: Kasus boleh singkat. Rangkai rencana operasi spesifik terhadap kasus dan SOP, termasuk indikasi berbasis input, persiapan, tahapan, peran, risiko relevan, monitoring, dan rujukan SOP. Jangan mengubah rencana menjadi bukti tindakan atau hasil operasi. Data belum tersedia hanya untuk fakta aktual, nilai ukur, hasil pemeriksaan, dan kejadian pelaksanaan yang memang tidak diberikan. ORIF/Open Reduction Internal Fixation selalu Mayor.'
WHERE feature_key = 'ai_surgery_planner';