---
deployment:
  tasks:
    - /bin/bash -lc 'set -o pipefail; /usr/bin/git -C /home/fouf9972/public_html/rh_ems archive --format=tar HEAD | /bin/tar --exclude=.cpanel.yml --exclude=.env -xf - -C /home/fouf9972/public_html/rh_ems'
